### ISSUE TITLE
MUS still not correct

### ISSUE THREAD

**Issue by rkkautsar** [crillab/gophersat#31]
Hi I saw a few closed issues and merged MR regarding incorrect MUS functionality but I still find it returning incorrect MUS

For example can try this problem:

```
p cnf 10 11
-1 0
-2 0
-3 0
-4 0
-5 0
-6 0
-7 0
-8 0
-9 0
-10 0
1 3 5 7 0
```

with latest commit in master (0b6a35c) it returns this as MUS:

```
> gophersat -mus unsat.cnf
p cnf 10 10
-1 0
-2 0
-3 0
-4 0
-5 0
-6 0
-7 0
-8 0
-9 0
-10 0
```

which shouldn't be correct, that's not UNSAT. The correct one should be

```
p cnf 10 5
-1 0
-3 0
-5 0
-7 0
1 3 5 7 0
```

**Comment by fdelorme** [comment]
Hello,

Indeed! There was a nasty bug there. The problem happens when computing MUSes on instances that can be solved by unit propagation (this is a tricky problem because the underlying solver does a ton of optimizations on these, which is good when you're just trying to solve an instance, but doesn't work when computing MUSes).

The bug seems to be fixed now, I added a test, please tell me if it solved the issue for you or not.

**Comment by rkkautsar** [comment]
yeah it works now, thanks a lot for the quick resolution!
